### ISSUE TITLE
Is MobulaOP support cupy？

### ISSUE THREAD

**Issue by chop2** [wkcn/MobulaOP#76]
Is possible support cupy (NumPy-like API accelerated with CUDA)？

for example:
a = cupy.array([1,2,3])
b = cupy.array([4,5,6])
out = cupy.empty(a.shape)
mobula.func.mul_elemwise(a.size, a, b, out)
-------------------------------------------------------------

Traceback (most recent call last):
  File "D:\Miniconda3\envs\python35\lib\site-packages\mobula\func.py", line 208, in __call__
    var, ptype, template_mapping, using_async)
  File "D:\Miniconda3\envs\python35\lib\site-packages\mobula\func.py", line 273, in _get_tensor_info
    raise TypeError()
TypeError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_mul_func.py", line 9, in <module>
    mobula.func.mul_elemwise(aa.size, aa, bb, outa)
  File "D:\Miniconda3\envs\python35\lib\site-packages\mobula\func.py", line 239, in __call__
    self.name, self.func.arg_types, list(map(type, args))))
TypeError: Unmatched parameters list of the function `mul_elemwise`:
        [const int32_t, <typename const T*>, <typename const T*>, <typename T*>]
                vs
        [<class 'int'>, <class 'cupy.core.core.ndarray'>, <class 'cupy.core.core.ndarray'>, <class 'cupy.core.core.ndarray'>]

**Comment by wkcn** [comment]
Thank you for the contribution in the PR #77 !
I have merged this PR : )

**Comment by wkcn** [comment]
Close it.
Thank you again!
